#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
cd ..

# Run User Study (done)
bash code/run_scripts/run_scripts_user_study/run_user_study_analysis.sh
bash code/run_scripts/run_scripts_user_study/run_create_plots_user_study.sh

# Run Experiment: Plant Disease Detection with hyperspectral data (done check Run 2704941)
bash code/run_scripts/run_scripts_hs/without_training/run.sh 
# bash code/run_scripts/run_scripts_hs/with_training/run.sh 

# Run Experiment: Plant Disease Detection with pseudo rgb data
bash code/run_scripts/run_scripts_rgb/without_training/run.sh
# bash code/run_scripts/run_scripts_rgb/with_training/run.sh

# Run Cluster Plot Generation (todo)
bash code/run_scripts/run_scripts_strategy_analysis/run_strategy_analysis.sh

# Run Experiment: Toy dataset -- fashion MNIST (done check Run 2717628)
bash code/run_scripts/run_scripts_fashion/run_fashion_mnist.sh